# frontend/Dockerfile.dev
FROM node:20-bullseye

WORKDIR /app

COPY . .

# Limpieza completa + instalación estable
RUN rm -rf node_modules package-lock.json && npm install

EXPOSE 5173

CMD ["npm", "run", "dev"]
