# Generated by Django 5.2.2 on 2025-09-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_coples', '0002_estadisticassistema_detecciondefecto_deteccionpieza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisiscople',
            name='imagen_procesada',
            field=models.ImageField(blank=True, help_text='Imagen procesada con resultados superpuestos (máscaras, bounding boxes, etc.)', null=True, upload_to='analisis/', verbose_name='Imagen procesada'),
        ),
    ]
